name: Build and Release Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build the application using PyInstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller GradingAutomation.spec --noconfirm

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: GradingAutomationBuild
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Download build artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: GradingAutomationBuild
          path: dist/

      # Create a new GitHub release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Zip the build artifacts
      - name: Zip Build Artifacts
        run: |
          cd dist
          zip -r GradingAutomationBuild.zip ./*

      # Upload release assets to the GitHub release
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/GradingAutomationBuild.zip
          asset_name: GradingAutomationBuild.zip
          asset_content_type: application/zip
